### ISSUE TITLE
ARM compilation - giflib error

### ISSUE THREAD

**Issue by M-Gonzalo** [schnaader/precomp-cpp#105]
I'm trying to compile precomp for arm, since it's getting more and more common every day, and there are fast and robust systems built around it.

But I'm getting this:

./contrib/giflib/egif_lib_gcc.c:116:29: error:

      use of undeclared identifier 'S_IREAD'
                          , S_IREAD | S_IWRITE);
                            ^
./contrib/giflib/egif_lib_gcc.c:116:39: error:

      use of undeclared identifier 'S_IWRITE'
                          , S_IREAD | S_IWRITE);
                                      ^
./contrib/giflib/egif_lib_gcc.c:124:29: error:

      use of undeclared identifier 'S_IREAD'
                          , S_IREAD | S_IWRITE);
                            ^
./contrib/giflib/egif_lib_gcc.c:124:39: error:

      use of undeclared identifier 'S_IWRITE'
                          , S_IREAD | S_IWRITE);
                                      ^

Do you support building precomp for ARM?

**Comment by schnaader** [comment]
Didn't have a working ARM version so far, but also tried to compile on my Android phone and my Raspberry Pi with the same result. These are some calls to file open routines that should be possible to replace so it compiles.

**Comment by schnaader** [comment]
@M-Gonzalo Could you check the arm-test branch I created? Had to do add additional checks and CMake specific stuff to your solution to enable building everywhere (Windows/Linux, ARM, ARM64).

The branch is based on the multithreaded-reconstruction branch and works for me on a Huawei tablet (ARM 64-bit) and a Motorola mobile phone (ARM 32-bit) - except for the packJPG and packMP3 bugs, these seem to be char-related and might be possible to fix later, too.

**Comment by schnaader** [comment]
There's a second branch called "arm-test-packjpg-packmp3-fix" now that is based on the arm-test branch and contains fixes for packJPG and packMP3, tested both of them on single files successfully.

I will do some further testing, but for now it looks good and I'm looking forward to merge this :+1:

**Comment by schnaader** [comment]
For the sake of completeness, here are build instructions for others that want to test the ARM compile:

```
git clone https://github.com/schnaader/precomp-cpp.git
cd precomp-cpp
git checkout arm-test-packjpg-packmp3-fix
cmake ./
make -j

```

**Comment by M-Gonzalo** [comment]
Will do! Expect results in the next few days.

**Comment by M-Gonzalo** [comment]
OK, sorry for the delay. I was in the middle of moving out to a new apartment and it was a mess.

I tested precomp against hundreds of GB of data on my phone using Termux, including thousands of jpgs and mp3s. Always roundtrip OK except for big files with a lot of streams (mostly apks). I keep seeing error reports about missing temp files.

**Comment by M-Gonzalo** [comment]
A different thing, Matthias' pack* libraries _appear_ to be significantly slower on ARM than on comparable x86_64 CPUs, but that is only a subjective observation...
