### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by M-Gonzalo** [schnaader/precomp-cpp#109]
File: https://cdn.download.clearlinux.org/releases/33510/clear/clear-33510-live-desktop.iso

CRC32: 13abfa78
MD5: 6dad4b6e0916812a01b8b119dfc0e789
Sha256: f9e3a3261ce4d86dcd12a80e1a26fb5a8f16cbc29c720c52164b62aa54db2a6d

![crash](https://user-images.githubusercontent.com/23223606/87876824-e31d5980-c9b0-11ea-9291-41e3dbbb3d54.png)

**Comment by schnaader** [comment]
Thanks! Overlooked one of the cases in the latest commit which led to this bug (on large deflate streams that aren't processed in memory, but on disk).
