### ISSUE TITLE
Bug Report: packMP3 error: ancilary prediction error

### ISSUE THREAD

**Issue by Sci3ntia** [schnaader/precomp-cpp#130]
When decompressing a precomp file, at around 52% it emits this (packMP3 error: ancilary prediction error, please report) error and stops, is it possible to either fix the behavior of packmp3 or skip that mp3 altogether? The file I have is 14GB large and doesn't have any backup copy stored outside of pcf, so any way to skip over errors like this and resume extracting the file is great.

**Comment by schnaader** [comment]
Skipping streams on reconstruction is not possible at the moment, but I could create a modified version of precomp (which version is your file compressed with, I'd assume 0.4.7?) and upload it here.

My plan for the modified version would be to not stop on the packMP3 error, but fill this MP3 part where the file could not be reconstructed with zeros, display a warning and resume extracting. This way, everything except that one part should get restored.
I'd also make the modified version extract that corrupted MP3 part from the pcf file and show the filename used in the warning, so you can upload it somewhere or send it to me by mail. I don't know if the corrupted part is useful without the original MP3, but it would at least make it possible to analyse the problem further.

In future versions, this "skip, resume, warn" would get the default behaviour. Additionally, an optional verification flag for MP3 streams (that verifies correct reconstruction when compressing) could be added. Of course, the best solution is to fix this in packMP3, but I guess this will take a while and it's useful to have a temporary workaround for this.

**Comment by Sci3ntia** [comment]
Thanks for replying so quickly! filling the mp3 with zeros should be perfect, since i'm restoring a tar archive. I'm actually using the linux x64 version 0.4.8.

**Comment by schnaader** [comment]
I've modified the current 0.4.8 master branch to resume on MP3 errors. You can either use the attached binary or compile the "issue_130" branch yourself. As I said, it might be useful if you upload the corrupt data files here, they'll be named "corrupt_pmp_xxx.dat".

Hope you can get back your .tar archive this way, good luck. Don't hesitate to write if you have questions or something goes wrong.

[precomp_corr.zip](https://github.com/schnaader/precomp-cpp/files/6736257/precomp_corr.zip)

**Comment by Sci3ntia** [comment]
sorry for the late reply, this worked very well for me and I was able to extract what I needed, thank you
