### ISSUE TITLE
Tutorial for compressing a folder

### ISSUE THREAD

**Issue by rayman3003** [schnaader/precomp-cpp#135]
I'm not good with command line apps. I read the "How to use it" section, but couldn't understand how to compress a folder using precomp-cpp.

For a example I have a folder containing some files named:

C:\AAA

What is the correct command line for compressing that folder?

Maybe a video or just an easy instruction would help me. Thank u.

**Comment by schnaader** [comment]
At the moment, Precomp can not create archives on its own, but only compress single files. So on Windows, you'd have to first put your folder into an uncompressed archive (e.g. using ZIP's or 7-Zip's "Store" method) creating a single file (e.g. AAA.zip). After that, you can use "precomp AAA.zip" to compress this file and "precomp -r AAA.pcf" to decompress the result. After decompressing, you'd have to decompress AAA.zip to get the folder back.

**Comment by rayman3003** [comment]
> At the moment, Precomp can not create archives on its own, but only compress single files. So on Windows, you'd have to first put your folder into an uncompressed archive (e.g. using ZIP's or 7-Zip's "Store" method) creating a single file (e.g. AAA.zip). After that, you can use "precomp AAA.zip" to compress this file and "precomp -r AAA.pcf" to decompress the result. After decompressing, you'd have to decompress AAA.zip to get the folder back.

Thank u very much for this solution.

Hope soon we would see the folder compressing support for precomp in the upcoming 0.5 version.

**Comment by rayman3003** [comment]
One more question:

What about I make an ISO image out of my folder, instead of zip & 7z?

Does the Precomp support compressing ISO format or not?

**Comment by schnaader** [comment]
That would also work, ISO images are usually uncompressed containers as well.

**Comment by M-Gonzalo** [comment]
If you suspect there are many duplicated files, you can use the WIM format, without compression, instead of TAR or ISO. WIM format stores only one copy of the data and then references. 7z can create uncompressed WIM images. And the wimlib library also works flawlessly with *NIX filesystems
