### ISSUE TITLE
Add basic multithreading (zLib bruteforce)

### ISSUE THREAD

**Issue by schnaader** [schnaader/precomp-cpp#15]
Multithreading would speed up the whole process a lot, the most time consuming routine (bruteforcing the 81 different zLib modes) should be fully parallelizable, but refactoring is needed to make it threadsafe.

**Comment by maki-chan** [comment]
This would be very useful, especially for brute mode, I think?
Unfortunately, I have many files where only brute mode would find something, but using brute mode with 1-2 GB files is just like hell.

**Comment by schnaader** [comment]
Obsolete with the change to preflate which uses a task pool for multithreading since preflate 0.3.3.
