### ISSUE TITLE
update packJPG to 2.5k and packMP3 to 1.0g

### ISSUE THREAD

**Issue by StephanBusch** [schnaader/precomp-cpp#33]
newest packJPG 2.5k can be found here
https://github.com/packjpg/packJPG

newest packMP3 can be found here:
http://packjpg.encode.ru/?page_id=19

**Comment by schnaader** [comment]
There's no need to update, the only change in both of them (aside from organisational things like Makefiles and readme) is the realloc bug that has already been merged. [commit in packJPG](https://github.com/packjpg/packJPG/commit/2d62eda2d75afac6a6b28458c3d966660922fa1b), [merge in Precomp](https://github.com/schnaader/precomp-cpp/commit/97081a423a1b719f4c0e01b88d139a4038853807).

I'll merge the version numbers and messages, though.

**Comment by schnaader** [comment]
Done. Found out that frealloc in packmp3.cpp still was the old version that could cause memory corruption, fixed!
