### ISSUE TITLE
Support "xz" (liblzma)

### ISSUE THREAD

**Issue by kraileth** [schnaader/precomp-cpp#40]
Currently precomp only supports compressing using bzip2 which is not too bad. However most people probably turn compression off and use another tool to manually apply stronger compression. XZ (http://tukaani.org/xz/) is already widely used in the *nix world and would be an excellent choice for a strong, yet not exotic compression method.

Even more interesting: Importing liblzma as contrib might also make it possible to allow for recompression of lzma streams. FreeBSD as well as a lot of Linux distributions use xz for their packages. Those often contain gzipped files like manpages and stuff like that. So if precomp could decompress lzma streams, streams with weak compression could be found and dealt with using recursion. A lot of open source projects offer source code in xz compressed tarballs, as well, and precompressing e.g. a project's source iso would greatly benefit from xz support.

**Comment by sftt** [comment]
liblzma, as far as I know, supports 2 formats: lzma & xz(lzma2)
xz fits for standalone file (*.tar.xz) better, while lzma(*.tar.lzma) is simpler for embeding in some other file container, without the well-designed XZ Header.
doubt if lzma/xz can be recompressed to identical bytes as the source, if success, it's a big step for precomp.

Even without that, adding lzma/xz to the on-the-fly compressor of precomp is worthy, considering 7-zip (origin of lzma/xz) not plan to add Jpeg algorithm.(https://sourceforge.net/p/sevenzip/discussion/45797/thread/558d8471/)
It's somewhat simple by first assigning 2=lzma,3=xz or so as compression_otf_method, and grab the example compress/decompress code from liblzma to own_fread/write() function in precomp.cpp

**Comment by sftt** [comment]
@kraileth #42 on-the-fly compress demo (decompression not implemented yet)

**Comment by schnaader** [comment]
Thanks, looks good after a quick glance! Will have a look at the pull request and merge.

**Comment by schnaader** [comment]
Adjusted some things and merged with the branch, see #51.

**Comment by schnaader** [comment]
Later, I might try to do lzma recompression, but that's something slightly different. On-the-fly compression works in 0.4.6.
