### ISSUE TITLE
DDS (DXT) recompression

### ISSUE THREAD

**Issue by StephanBusch** [schnaader/precomp-cpp#53]
DDS files that use DXT compression can be also recompressed.
This would be a nice feature of precomp.

There's a page describing decompression:
http://matejtomcik.com/Public/KnowHow/DXTDecompression/

**Comment by schnaader** [comment]
Closing this for now. Decompression is easy, but the format is lossless, so even recompressing the decompressed data with PAQ is a bit larger. Also, the data has much structure, but the obvious transforms (e.g. splitting colors and color indices) don't improve lzma compression. One result from these tests on a DXT1 compessed texture:

|compression|size (in bytes)|
|---|---|
|Original | 393,344 (100%) |
|Precomp| 83,865 (21%)|
|paq8px_v161 -4| 60,266 (15%)|
|Converting to PNG -> Precomp| 208,106 (53%)|
|Converting to PNG -> FLIF -e -N| 146,672 (37%)|
|Converting to BMP -> paq8px_v161 -4| 64,335 (16%)|

There also is a good [blog article](https://www.jonolick.com/home/dxt-compression-part-3-transposes) on this topic by Jon Olick that comes to similar results (best transpose improvement on lzma: 0.5%)
