### ISSUE TITLE
precomp segfaults for this file.

### ISSUE THREAD

**Issue by dElogics** [schnaader/precomp-cpp#59]
pre compressing this file -- 
[precomp_segfault.zip](https://github.com/schnaader/precomp-cpp/files/981589/precomp_segfault.zip)
with command line -- 

-cn -oprecomp_tar

segfaults precomp on LInux 64

I tried to get the BT, but the debugging symbols where not there in the binary version and the one that I built from git. I tried changing the CFLAGS and added -ggdb, but the debugging symbols still got stripped. On changing the optimization levels to -O0 for all libraries, solved the problem but of course it's a bad solution.

**Comment by dElogics** [comment]
It's giflib. Disabling it completes the precomp.

**Comment by sftt** [comment]
try on Win7 64bit.
- precomp_segfault.zip : no fault & no gain
- -intense precomp_segfault.zip : no fault & no gain
- precomp_segfault.tar(extracted from the zip) : no fault
- -intense precomp_segfault.tar : **fault on 59.82%**
- -v -intense precomp_segfault.tar : no fault, suggest -zl18,68,69,82,95 -d0
- -intense -d0 precomp_segfault.tar : no fault
- -intense -d10 precomp_segfault.tar : no fault
- -intense -zl18,68,69,82,95 precomp_segfault.tar : **fault on 59.82%**

**Comment by schnaader** [comment]
Regression from 0.4.5 (where everything works according to a quick test), one of the culprits is a GIF stream at position 1260117 (60.09%), but there seem to be other problems, as the following gives no segfault on my machine (Win7 64bit, Precomp 0.4.6 commit d9f61c6):

precomp -cn -intense -zl18,68,69,82,95 -v -i1254601 -i1244353 -i1237086 -i1162009 -i1146093 -i1138392 precomp_segfault.tar

(it basically ignores several streams before the GIF stream, but not the GIF stream itself)

OTOH, undefined behaviour leads to undefined behaviour, so you never know...

**Comment by dElogics** [comment]
Mine is a Linux machine.

**Comment by dElogics** [comment]
Segfaults 4.5 also.

**Comment by schnaader** [comment]
Debugging with Visual Studio worked good. This way, the error could be isolated to testing a small GIF file (attached). The image is 1x1 pixel, but has no colormap, so that the function EGifPutImageDesc returns an error code - this code was unhandled and led to accessing uninitialized memory.

![segfault](https://user-images.githubusercontent.com/7848769/26862880-e356995e-4b4e-11e7-9389-294b64038917.gif)

**Comment by dElogics** [comment]
Thanks.
