### ISSUE TITLE
`make install` target

### ISSUE THREAD

**Issue by ilovezfs** [schnaader/precomp-cpp#68]
Hi,

In the new Homebrew formula for precomp, which I have just merged, we're using

```
    system "make"
    bin.install "precomp"
```

It would be great if instead we could use

```
    system "make", "PREFIX=#{prefix}", "install"
```

Would you be willing to add a `make install` target?

**Comment by schnaader** [comment]
Unfortunately, as I wrote in #60, I don't have any developing experience with macOS and only a little with Makefiles, so could you describe what is needed a bit more (e.g. what should the "install" target do, what's `prefix` for?)

As far as I see in [the commit](https://github.com/Homebrew/homebrew-core/commit/9626b9dbd1ff4fe17bf4b6a49baee54ea6a8c0e3), it is based on 0.4.5 which is OK, though it could be updated to the new version 0,4.6. I also could merge Makefile.osx from maki-chan's branch so it would be a bit more straightforward to build without the replacements (`make -f Makefile.osx`) and add the `install` target to it.

**Comment by ilovezfs** [comment]
Here are some examples:
https://github.com/micropython/micropython/blob/master/ports/unix/Makefile#L196-L197

https://github.com/jordansissel/grok/blob/master/Makefile#L9
https://github.com/jordansissel/grok/blob/master/Makefile#L94

https://github.com/zpaq/zpaq/blob/master/Makefile#L5-L6
https://github.com/zpaq/zpaq/blob/master/Makefile#L24-L25

Let me know if you need more!

**Comment by schnaader** [comment]
@ilovezfs
Sorry, been busy the last weeks, so the change delayed. GitHub auto-fixed this, but don't hesitate to reopen if it doesn't work yet.

**Comment by ilovezfs** [comment]
@schnaader looks good. Almost there. It's just missing the step that creates the `bin` directory.

```
install: contrib $(PROGNAME)
	install -m 555 ./precomp $(BINDIR)
```
That will actually install precomp into $(PREFIX) and give it the file the name "bin"

Instead, you need
```
install: contrib $(PROGNAME)
	install -d $(BINDIR)
	install -m 555 ./precomp $(BINDIR)
```
which will create the directory $(BINDIR) and then install precomp into that directory with the file name "precomp"

**Comment by ilovezfs** [comment]
(also the `./` isn't actually needed)

**Comment by ilovezfs** [comment]
>but don't hesitate to reopen if it doesn't work yet.

Just an FYI that users cannot reopen an issue if they weren't the one who closed it.

**Comment by schnaader** [comment]
> Just an FYI that users cannot reopen an issue if they weren't the one who closed it.
Oh, good to know, thanks!

**Comment by ilovezfs** [comment]
@schnaader Thanks @schnaader!
