### ISSUE TITLE
Using -zl is broken in 0.4.7dev

### ISSUE THREAD

**Issue by schnaader** [schnaader/precomp-cpp#76]
The MTF change broke the -zl parameter. In [this part of commit 74a431](https://github.com/schnaader/precomp-cpp/commit/74a431341bc2ad93d368cf772922495b57851a7d#diff-21b131e650b48886c62a56609a98035fL3194), it can be see why:

before: `if (levels_sorted[index] == -1) break;` 
after: `if (comp_mem_level_count[index] == -1) break;`

Before the change, the levels were sorted, so those with -1 (the disabled ones that weren't given in the -zl parameter) were at the end of the list and we could break out of the loop because no other levels would follow. After the change, however, this is not true anymore.

To reproduce the bug, any file that gives -zl suggestions can be used. If the suggested parameters is different to "-zl11", using it will skip any streams.

@MarcioPais : I'm not sure about the correct solution, replacing the `break` with a `continue` seems to be a good workaround at a first glance, but it also seems like the disabled levels should be removed from the MTF list completely.

**Comment by schnaader** [comment]
@MarcioPais: Fixed this with the solution above (replacing `break` with `continue`), it works and I think the overhead of up to 80 `continue` calls is negligible, so I didn't bother with removing the levels from the MTF list.

**Comment by MarcioPais** [comment]
I completely forgot about the -zl parameter, sorry. Your solution seems like a good workaround, and is simpler than modifying the zlib class to build a list with just the enabled zlib parameter combinations.
