### ISSUE TITLE
Support for Intel IPP Zlib Source

### ISSUE THREAD

**Issue by AmsalKhan** [schnaader/precomp-cpp#80]
There is no doubt that Intel Optimized Zlib source files are far faster than normal zlib, but I tried making with Intel IPP source, and it unexpectedly hangs the precomp.exe at some random percentage before 15%. There is whole zlib source code implementation already done by Intel in there Intel IPP components examples. I have attached the patched Intel IPP source with the Readme.html file, well for compiling this you sure need IntelC++ on your operating system.
I tried myself for making it compatible, but I won't be able to make it, I also couldn't find why its hanging at some point as I couldn't debug as well, so in this case I thought only the creator can tell well.
Here the Intel Page regarding the zlib - https://software.intel.com/en-us/articles/how-to-use-zlib-with-intel-ipp-opertimization
[zlib-1.2.11-ipp.zip](https://github.com/schnaader/precomp-cpp/files/1848079/zlib-1.2.11-ipp.zip)

**Comment by schnaader** [comment]
I'll have a look at it, but I see this as a very low priority thing. The reason for this is that we'll get more and more in the direction of using a modified or own implemention of deflate routines like difflate that offer better recompression (basically, solving of #21 ) and trade off speed for that.

Nevertheless, there seem to be free options for using Intel IPP which might give some speedup even with modified zlib/deflate code.

**Comment by Optimus17** [comment]
Yes, but I think you can implement it in couple of hours, probably it just needed some code fixes for getting it worked. If you need I can provide you Intel Parallel Studio XE license and setup files to get it installed on your system and it can directly attached to Visual Studio 2012/15/17

Anyways, thanks for taking it in considerations.

Best Regards

**Comment by M-Gonzalo** [comment]
If what you want is replace zlib with Intel'implementation, it just won't work. They don't produce identical output. Compatible, yes, but precomp needs to be able to losslessly rebuild the original stream.

**Comment by Optimus17** [comment]
Yes @M-Gonzalo you are right, I tried the same and it actually worked with some other programs, but it was very slow.

**Comment by schnaader** [comment]
Obsolete because of preflate integration, closed.
