### ISSUE TITLE
Compiling development branch using GCC

### ISSUE THREAD

**Issue by M-Gonzalo** [schnaader/precomp-cpp#83]
I'm refering to https://github.com/deus-libri/preflate/issues/1#issue-353220713

The inclusion of the preflate library breaks the compiling process using the 'make' command.

**Comment by M-Gonzalo** [comment]
Thanks for having a look at it. 
Apparently, the compiling process works, but I'm not able to finish it due to an error:

<pre>[ 78%] <font color="#44AA44">Building CXX object CMakeFiles/precomp.dir/contrib/preflate/preflate_complevel_estimator.cpp.o</font>
In file included from <font color="#FFFFFF"><b>/home/gonzalo/Downloads/tmp_Opera/precomp-cpp-develop/contrib/preflate/preflate_predictor_state.h:23:0</b></font>,
                 from <font color="#FFFFFF"><b>/home/gonzalo/Downloads/tmp_Opera/precomp-cpp-develop/contrib/preflate/preflate_complevel_estimator.h:18</b></font>,
                 from <font color="#FFFFFF"><b>/home/gonzalo/Downloads/tmp_Opera/precomp-cpp-develop/contrib/preflate/preflate_complevel_estimator.cpp:17</b></font>:
<font color="#FFFFFF"><b>/home/gonzalo/Downloads/tmp_Opera/precomp-cpp-develop/contrib/preflate/preflate_seq_chain.h:22:3:</b></font> <font color="#FF8787"><b>error: </b></font>‘<font color="#FFFFFF"><b>uint16_t</b></font>’ does not name a type; did you mean ‘<font color="#FFFFFF"><b>u_int16_t</b></font>’?
   <font color="#FF8787"><b>uint16_t</b></font> distToNext;
   <font color="#FF8787"><b>^~~~~~~~</b></font>
   <font color="#44AA44">u_int16_t</font>
<font color="#FFFFFF"><b>/home/gonzalo/Downloads/tmp_Opera/precomp-cpp-develop/contrib/preflate/preflate_seq_chain.h:23:3:</b></font> <font color="#FF8787"><b>error: </b></font>‘<font color="#FFFFFF"><b>uint16_t</b></font>’ does not name a type; did you mean ‘<font color="#FFFFFF"><b>u_int16_t</b></font>’?
   <font color="#FF8787"><b>uint16_t</b></font> length;
   <font color="#FF8787"><b>^~~~~~~~</b></font>
   <font color="#44AA44">u_int16_t</font>
<font color="#FFFFFF"><b>/home/gonzalo/Downloads/tmp_Opera/precomp-cpp-develop/contrib/preflate/preflate_seq_chain.h:48:10:</b></font> <font color="#FF8787"><b>error: </b></font>‘<font color="#FFFFFF"><b>uint16_t</b></font>’ does not name a type; did you mean ‘<font color="#FFFFFF"><b>u_int16_t</b></font>’?
   inline <font color="#FF8787"><b>uint16_t</b></font> len() const {
          <font color="#FF8787"><b>^~~~~~~~</b></font>
          <font color="#44AA44">u_int16_t</font>
<font color="#FFFFFF"><b>/home/gonzalo/Downloads/tmp_Opera/precomp-cpp-develop/contrib/preflate/preflate_seq_chain.h:</b></font> In constructor ‘<font color="#FFFFFF"><b>PreflateSeqIterator::PreflateSeqIterator(const SeqChainEntry*, unsigned int)</b></font>’:
<font color="#FFFFFF"><b>/home/gonzalo/Downloads/tmp_Opera/precomp-cpp-develop/contrib/preflate/preflate_seq_chain.h:36:31:</b></font> <font color="#FF8787"><b>error: </b></font>‘<font color="#FFFFFF"><b>const struct SeqChainEntry</b></font>’ has no member named ‘<font color="#FFFFFF"><b>distToNext</b></font>’
     , curDist(chain_[refPos_].<font color="#FF8787"><b>distToNext</b></font>) {
                               <font color="#FF8787"><b>^~~~~~~~~~</b></font>
<font color="#FFFFFF"><b>/home/gonzalo/Downloads/tmp_Opera/precomp-cpp-develop/contrib/preflate/preflate_seq_chain.h:</b></font> In member function ‘<font color="#FFFFFF"><b>bool PreflateSeqIterator::next()</b></font>’:
<font color="#FFFFFF"><b>/home/gonzalo/Downloads/tmp_Opera/precomp-cpp-develop/contrib/preflate/preflate_seq_chain.h:52:40:</b></font> <font color="#FF8787"><b>error: </b></font>‘<font color="#FFFFFF"><b>const struct SeqChainEntry</b></font>’ has no member named ‘<font color="#FFFFFF"><b>distToNext</b></font>’
     curDist += chain[refPos - curDist].<font color="#FF8787"><b>distToNext</b></font>;
                                        <font color="#FF8787"><b>^~~~~~~~~~</b></font>
<font color="#FFFFFF"><b>/home/gonzalo/Downloads/tmp_Opera/precomp-cpp-develop/contrib/preflate/preflate_seq_chain.h:</b></font> At global scope:
<font color="#FFFFFF"><b>/home/gonzalo/Downloads/tmp_Opera/precomp-cpp-develop/contrib/preflate/preflate_seq_chain.h:62:3:</b></font> <font color="#FF8787"><b>error: </b></font>‘<font color="#FFFFFF"><b>uint16_t</b></font>’ does not name a type; did you mean ‘<font color="#FFFFFF"><b>u_int16_t</b></font>’?
   <font color="#FF8787"><b>uint16_t</b></font> heads[256];
   <font color="#FF8787"><b>^~~~~~~~</b></font>
   <font color="#44AA44">u_int16_t</font>
<font color="#FFFFFF"><b>/home/gonzalo/Downloads/tmp_Opera/precomp-cpp-develop/contrib/preflate/preflate_seq_chain.h:70:3:</b></font> <font color="#FF8787"><b>error: </b></font>‘<font color="#FFFFFF"><b>uint16_t</b></font>’ does not name a type; did you mean ‘<font color="#FFFFFF"><b>u_int16_t</b></font>’?
   <font color="#FF8787"><b>uint16_t</b></font> len(const unsigned refPos) const {
   <font color="#FF8787"><b>^~~~~~~~</b></font>
   <font color="#44AA44">u_int16_t</font>
<font color="#FFFFFF"><b>/home/gonzalo/Downloads/tmp_Opera/precomp-cpp-develop/contrib/preflate/preflate_seq_chain.h:</b></font> In member function ‘<font color="#FFFFFF"><b>bool PreflateSeqChain::valid(unsigned int) const</b></font>’:
<font color="#FFFFFF"><b>/home/gonzalo/Downloads/tmp_Opera/precomp-cpp-develop/contrib/preflate/preflate_seq_chain.h:68:38:</b></font> <font color="#FF8787"><b>error: </b></font>‘<font color="#FFFFFF"><b>struct SeqChainEntry</b></font>’ has no member named ‘<font color="#FFFFFF"><b>distToNext</b></font>’
     return prev[refPos - totalShift].<font color="#FF8787"><b>distToNext</b></font> != 0xffff;
                                      <font color="#FF8787"><b>^~~~~~~~~~</b></font>
CMakeFiles/precomp.dir/build.make:2486: recipe for target &apos;CMakeFiles/precomp.dir/contrib/preflate/preflate_complevel_estimator.cpp.o&apos; failed
make[2]: *** [CMakeFiles/precomp.dir/contrib/preflate/preflate_complevel_estimator.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target &apos;CMakeFiles/precomp.dir/all&apos; failed
make[1]: *** [CMakeFiles/precomp.dir/all] Error 2
Makefile:83: recipe for target &apos;all&apos; failed
make: *** [all] Error 2
</pre>

**Comment by Diazonium** [comment]
The uint16_t errors look very familiar to me, but I have only encountered them when the compiler was too old and did not support C++11. Maybe some include is missing? Try adding #include <cstdint> to preflate_seq_chain.h and other source files, and make sure the compiler is set to use C++11 or 14

**Comment by M-Gonzalo** [comment]
> The uint16_t errors look very familiar to me, but I have only encountered them when the compiler was too old and did not support C++11. Maybe some include is missing? Try adding `#include <cstdint>` to preflate_seq_chain.h and other source files, and make sure the compiler is set to use C++11 or 14

Will try. Thanks for the tip.

**Comment by M-Gonzalo** [comment]
Finally, adding 
`#include <cstdint>`
to these two files:

./contrib/preflate/preflate_predictor_state.h
./contrib/preflate/preflate_seq_chain.h

...did the trick. I didn't test it on Windows though. I don't know if it breaks something but at least on linux compiles just fine.

**Comment by Diazonium** [comment]
`<cstdint>` is a standard C/C++ library header file, including it really should not break anything, except if the compiler does not support it.
So this may break really old versions of MSVC++, that do not support C++11. But that should not be an issue, since people on windows can just use TDM-GCC or some other MinGW64 based toolchain to get a sufficiently recent version of GCC.

**Comment by schnaader** [comment]
Thanks @M-Gonzalo and @Diazonium for further investigation, fixed this and verified that the Windows build still works.

**Comment by M-Gonzalo** [comment]
> @M-Gonzalo : If you run cmake from the command line, call it like this:
> "cmake -DCMAKE_BUILD_TYPE=Release path_to_cmake_lists/"
> It will create a debug build by default, which will be much larger (for me: 2,4 MB for debug, 1,2 MB for release) and slower.

duh!! Didn't think of that. Now it is indeed a lot faster (about 2.5x)
Thanks!
