### ISSUE TITLE
ZIP recognition failure

### ISSUE THREAD

**Issue by M-Gonzalo** [schnaader/precomp-cpp#84]
Quoting [a post on encode.ru](https://encode.ru/threads/2948-Preflate-An-open-source-recompressor-for-non-zlib-deflate?p=56719&viewfull=1#post56719):

It appears that the preflate changes tampered with the zip header recognition somehow in precomp. I cannot reproduce the issue on every zip but I managed to narrow it down to a subset of files consisting of .docx documents exported from Google Docs and documents on the ODF format saved by LibreOffice. Maybe that info will help you to reproduce the problem. .jar java applications are also affected, but I don't know with what software they were created. Usually the streams are at last recognized in brute mode but should it be off, no recompression happens whatsoever, while normal precomp doesn't need to have -brute active to process them.

This is the output of both for a bundle of 18 of said files from my docs folder on a tar archive; each program ran with the setting "-cn -t-nj" to avoid png and jpg recognition:

Precomp:

```
Recompressed streams: 281/283
ZIP streams: 281/283
```
Preflate:

```
Recompressed streams: 14/14
ZIP streams: 14/14

```

This is preflate for a folder with +2000 .jar and a few .zip. Notice the huge amount of 'brute mode streams' compared to the little amount of 'zip streams':

```
Recompressed streams: 37912/37947
PDF streams: 24/24
ZIP streams: 4191/4191
PNG streams: 2961/2961
PNG streams (multi): 115/115
GIF streams: 591/626
JPG streams: 14/14
zLib streams (intense mode): 1353/1353
Brute mode streams: 28663/28663

```

**Comment by schnaader** [comment]
Attached a test file, TeX project generated with Overleaf. Results:
`Precomp 0.4.6: 249.161 bytes, 7/9 ZIP`
`Preflate 0.4.133: 268.949 bytes, no ZIP`
`Preflate 0.4.133 -brute: 228.389 bytes, 6/6 brute`
`Precomp 0.4.7dev (with fix): 228.261 bytes, 9/9 ZIP`

[preflate-test.zip](https://github.com/schnaader/precomp-cpp/files/2392080/preflate-test.zip)
