### ISSUE TITLE
Preflate related crash

### ISSUE THREAD

**Issue by schnaader** [schnaader/precomp-cpp#89]
The file "gam.tar.001.019.001" (15.2 MB, [download from Google Drive](https://drive.google.com/file/d/1Nq4UZ11lPzsTfAnT7DG1tyzyLO82w9sr/view)) crashes precomp.

This seems to be related to the latest preflate changes, as it didn't crash the [experimental preflate 0.3.2 version](https://github.com/deus-libri/precomp-cpp/tree/78b918dc18a82fc91622b04588aedf66e37e613b/bin). Additionally, the file position where it happens isn't always the same, so it could be some bug in the thread pool.

Unfortunately, the crash doesn't happen for me when debugging in Visual Studio.

**Comment by deus-libri** [comment]
It's easy enough to trigger in VS: release build with debug info. The pointer to the virtual method table for one of the decoder objects is junked. So it is not a "harmless out-of-bounds" read like #88.
If I disable multithreading in preflate decoder, it doesn't crash. I guess I know how I will spend this weekend. ;)

**Comment by deus-libri** [comment]
I've updated preflate to v0.3.5 which should solve this issue.

**Comment by schnaader** [comment]
Works for me, thanks for the quick fix!
