### ISSUE TITLE
Parameter parsing ignores additional characters after switches

### ISSUE THREAD

**Issue by schnaader** [schnaader/precomp-cpp#9]
At the moment, additional characters after valid switches are ignored, which can lead to unwanted behaviour. For example, an user could call `precomp -cn-v file` (no space before `-v`) and be surprised that verbose mode is off.

This should lead to an error ("superfluous characters in switch -cn-v") instead of ignoring the characters.

**Comment by guptaprince** [comment]
this can be done only for options that don't take only numbers?

**Comment by schnaader** [comment]
Yes, it has to be done only for those as the options with numbers won't allow something like "12345-v".
